core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_app.urls', namespace='test'))
]

core/test_app/urls.py
from django.urls import path

from .views import IndexView, DetailView, ResultView, vote

app_name = 'test'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('<int:pk>/', DetailView.as_view(), name='question_detail'),
    path('<int:pk>/results/', ResultView.as_view(), name='question_results'),
    path('<int:question_id>/vote/', vote, name='question_vote'),
]

core/test_app/models.py
from django.utils import timezone
import datetime

from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200, verbose_name='question text')
    published_date = models.DateTimeField(verbose_name='date published')

    def __str__(self):
        return str(self.question_text)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.published_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='question')
    choice_text = models.CharField(max_length=200, verbose_name='choice text')
    votes = models.PositiveIntegerField(default=0, verbose_name='number of votes')

    def __str__(self):
        return str(self.choice_text)


q = Question(question_text="what's up?")
from test_app.models import Question, Choice

core/test_app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.utils import timezone

from .models import Question, Choice


class IndexView(ListView):
    #latest_question_list = Question.objects.order_by('-published_date')[:5]
    #output = ', '.join([q.question_text for q in latest_question_list])
    #template = loader.get_template('test_app/index.html')
    #context = {'latest_question_list': latest_question_list}
    #return HttpResponse(template.render(context, request))

    #return render(request, 'test_app/index.html', context)

    template_name = 'test_app/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        return the last 5 published question (not including published in the future)
        """

        return Question.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:5]


#def detail(request, question_id):
    #try:
        #question = Question.objects.get(pk=question_id)
        #context = {'question': question}
    #except Question.DoesNotExist:
        #raise Http404('Question does not exist')

    #question = get_object_or_404(Question, pk=question_id)
    #context = {'question': question}

    #return render(request, 'test_app/detail.html', context)

class DetailView(DetailView):
    model = Question
    context_object_name = 'question'
    template_name = 'test_app/detail.html'

    def get_queryset(self):
        """
        Excluded any questions that aren't published yet
        """
        return Question.objects.filter(published_date__lte=timezone.now())


#def result(request, question_id):
#    question = get_object_or_404(Question, id=question_id)
#    return render(request, "test_app/results.html", {'question': question})

class ResultView(DetailView):
    model = Question
    context_object_name = 'question'
    template_name = 'test_app/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, id=question_id)

    try:
        selected_choices = question.choice_set.get(pk=request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        return render(request, 'test_app/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice"
        })

    else:
        selected_choices.votes += 1
        selected_choices.save()
        return HttpResponseRedirect(reverse('test:question_results', args=(question.id, )))

core/test_app/templates/test_app/detail.html
<h1>{{ question.question_text }}</h1>
<p>{{question.published_date}}</p>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'test:question_vote' question.pk %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

core/test_app/templates/test_app/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'test:question_detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}

core/test_app/templates/test_app/results.html
<h1>{{question.question_text}}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href="{% url 'test:question_detail' question.id %}">Vote again?</a>